### ISSUE TITLE
Add API extension for reconnection triggers

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-java#116]
Description:

Currently, the reconnection procedures (both partial and full) are performed only at the event of losing connection. There are other cases when it is necessary to perform reconnection, for example:
1) Not all Tarantool instances are available at the moment of the connection and we need to connect to the others when they become available
2) New instances are added due to the scaling under load
3) Hot datacenter switchover: new instances are connected and then the old ones must be turned off 
4) Rolling updates of the instances -- instances are rebooted one by one

All cases above require a partial reconnection. But there may be also cases that require full reconnection -- it may be decided by the user. I can think of one example, but I'm not sure that full reconnection is necessary -- the storage has degraded and we need to stop the load from the application.

Proposal:

 - Implement an API extension (new method, event, etc) that triggers the partial reconnection procedure.
 - Add an address provider example with triggering reconnection when the pool of addresses is updated (via API or via periodic polling).

Closes #115

**Comment by vrogach2020** [comment]
This case is partially covered by https://github.com/tarantool/cartridge-java/pull/160
