### ISSUE TITLE
No tests for mapper Date

### ISSUE THREAD

**Issue by ArtDu** [tarantool/cartridge-java#130]
Create a test that shows the mapping behavior of the Date data type from java to tarantool. What type of data is the conversion expected to be? (Number by my testing)

```java
@Schema(description = "Some date")
private Date date;
```

**Comment by vrogach2020** [comment]
Also

**Comment by vrogach2020** [comment]
Sorry misclick..
We need also to discuss what to do with Date converters in springdata..
It seems if do not need Date converters in two libraries.

**Comment by ArtDu** [comment]
Migrate to https://github.com/tarantool/cartridge-springdata/issues/57
