### ISSUE TITLE
Change ddl functions in readme and tests

### ISSUE THREAD

**Issue by ArtDu** [tarantool/cartridge-java#142]
How the `cartridge` and` ddl` changes appeared, we haven't changed the driver:
https://github.com/tarantool/cartridge/commit/04f6747e2ea3fb1b1115b70bdcb494b66d92b9b4
https://github.com/tarantool/ddl/commit/4b5961fef91712728fe48d4d3bd2361893d76ba1

Now we are not needed to use `get_schema = require('ddl').get_schema` on storages, because `ddl` is in` _G`, implicitly using the `ddl-manager` role.  
>3. Add the following lines into any [storage role](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_dev/#cluster-roles)
>enabled on all storage instances in your cluster. The lines go into role API declaration section; in other words, into the returned table
>
>```lua
>return {
>    role_name = 'app.roles.api_storage',
>    init = init,
>    ...
>    get_schema = require('ddl').get_schema,
>    ...
>    dependencies = {
>        'cartridge.roles.crud-storage'
>    }
>}
>```
>

It is also worth considering to accepting a scheme, why do we need to go to the storage, if we can take a scheme on a router simply by calling `ddl.get_schema`.

>4. Add the following lines into any [router role](https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_dev/#cluster-roles)
>enabled on all router instances in your cluster to which the driver will be connected to:
>
>```lua
>...
>
>-- Add the following variables
>local cartridge_pool = require('cartridge.pool')
>local cartridge_rpc = require('cartridge.rpc')
>
>...
>
>-- Add the following function
>local function get_schema()
>    for _, instance_uri in pairs(cartridge_rpc.get_candidates('app.roles.api_storage', { leader_only = true })) do
>        return cartridge_rpc.call('app.roles.api_storage', 'get_schema', nil, { uri = instance_uri })
>    end
>end
>
>...
>
>local function init(opts)
>    ...
>    rawset(_G, 'ddl', { get_schema = get_schema }) -- Add this line
>    ...
>end
>```

From my questions, how does it all work on `tdg`?

**Comment by iDneprov** [comment]
4 sp wasted trying to add migrations instead of changing model in storage role. But Tarantool 2.10 CE does not support migrations. So we decided not to use migrations.
1 sp will be spanned on documentation.
