### ISSUE TITLE
Check that cartridge-java does not create connections above limit

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/cartridge-java#149]
We observe a strange behavior of a cluster. 
It looks like java client creates lots of connections (10 times more than expected).
Cluster config:
~ 48 routers, 200 storages
~ 20 clients, 192 connections per client

Expected number of IPROTO connections in cluster ~ 5000.
Probably after some network errors number of connections increased up to 55k and remain stable for about 24 hours. 

What we can do here:

- [ ] add connection count metrics to java client
- [ ] cover connection limit by unit / integration tests. Consider retrying and non-retrying configurations

**Comment by vrogach2020** [comment]
Also we should check how Netty closes sockets and if it is handled in proper way.
See https://stackoverflow.com/questions/28812858/netty-server-does-not-close-release-socket

**Comment by wey1and** [comment]
During discussions and debugging, the following problems were identified:
1) We probably have a race condition when accessing the ConnectionRegister - we need to add thread synchronization in the `AbstractTarantoolConnectionManager` class.
2) It is necessary to add meaningful metrics inside the connection mechanism.
3) It is necessary to add a connection strategy, where the user can specify the following parameters: when and under what circumstances it is necessary to reconnect.
4) Add more logging to `AbstractTarantoolConnectionManager`.
5) We need to think about configuring the number of `nioEventLoops` threads. Why is their number growing and do we need to stop it?
