### ISSUE TITLE
Correct readme sections 'Quickstart' and 'Cluster Tarantool client'

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/cartridge-java#185]
1 In the section "Cluster Tarantool client" we give an example of using built-in discovery modules. 
This can confuse customers - they think that discovery is always necessary.
It seems we need to rename the section to "Using service discovery" or somethink like that.

2 Also in the example code we use "container" object which was copy-pasted from integration tests. This also confuses the customers because they don't know anything  yet about containers while reading readme the first time

3 In quickstart p.9  we use 'mapperFactory' but it's not described how to create it

4 In quickstart we set up cartridge cluster (probably with sharding). But client is set-up without proxyMapping so CRUD calls do not work 

5 in get_schema() example implementation add note that storage role name must be corrected according to cluster config

**Comment by iDneprov** [comment]
Implemented in Quickstart #305
