### ISSUE TITLE
Add  TarantoolClient.call with bucket_id 

### ISSUE THREAD

**Issue by vlalykin** [tarantool/cartridge-java#219]
In operations on an entity (TarantoolClient.insert, update, delete, replace, upsert), you can explicitly set the bucket_id (entity field), or implicitly (the bucket_id field is passed empty, which will cause the router to calculate this field according to the given data scheme rules). But the API for calling a stored procedure (TarantoolClient.call) does not provide such opportunity.

Goal: transparent code execution on storage nodes, without writing additional code on the router's side (because we do not write code on the router for insert, update, delete, replace, upsert).

Like [Add call(functionName, args, spaceName) like callForTuple in cartridge-springdata](https://github.com/tarantool/cartridge-java/issues/211), we want to set not only the space name, but also guarantee that the procedure is executed on only one shard of the cluster, that is, set the bucket_id (explicitly or implicitly). 

We are talking about TarantoolClient.call calls:
```
// 1. the call goes to an explicitly specified shard with the specified bucket_id
TarantoolResult<TarantoolTuple> result = client.call(
        "function_name",
        args
        spaceName,
        bucket_id
).get();

// 2. bucket_id is determined on the router's side  ACCORDING TO THE SAME RULES as for insert, update, delete, replace, upsert.
// May be a subset of API#1 if bucket_id = null
TarantoolResult<TarantoolTuple> result = client.call(
        "function_name",
        args
        spaceName
).get();

// 3. more generally, calling with custom mappers
TarantoolResult<TarantoolTuple> result = client.call(
        "function_name",
        args
        spaceName,,
        bucket_id
        argumentsMapper,
        resultMapper
).get();
```

**Comment by vrogach2020** [comment]
See also https://github.com/tarantool/cartridge-springdata/issues/33

**Comment by ArtDu** [comment]
Ideally, we should be able to pass all CRUD parameters

**Comment by ArtDu** [comment]
This is the wrong issue because with the call method we can pass whatever you want(everything that converters support to encode to msgpack).
For example, you can pass bucket_id to select with call like that:
```
client.call("crud.select", Arrays.asList("test__profile", null, Map.of("first", 1))).get()
```

But we can't pass bucket_id into our proxy method like https://github.com/tarantool/cartridge-java/blob/57af227042cdc6402749e39a70a49ae61b94eb9a/src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java#L158 . That's the reason why I've created more correct ticket #270

**Comment by vlalykin** [comment]
Здесь речь все таки шла о прокси для вызова stored procedure (не о вызовах crud-операций): 

> But the API for calling a stored procedure (TarantoolClient.call) does not provide such opportunity.

как с явным указанием bucket_id, так и без оного - то есть bucket_id мог бы вычисляться на роутере по тем же правилам, как он сейчас вычисляется на роутере через прокси

из java мы дергаем select/update и т.п., не задумываясь о том, на каком шарде произойдет эта операция. тоже самое хотелось бы для stored procedure.

**Comment by ArtDu** [comment]
> из java мы дергаем select/update и т.п., не задумываясь о том, на каком шарде произойдет эта операция. тоже самое хотелось бы для stored procedure.

Да, в теории можно делать call на определенном шарде через роутер. Это делается через vshard API, но пользователю все равно стоит задумываться над добавлением функции на сторадже, которую нужно будет вызвать. Поэтому мы не планировали добавлять такой функционал, если нужно его всегда можно добавить пользователю самостоятельно просто спроксировать вызов `vshard.call*` через client.call

**Comment by vlalykin** [comment]
- Явно использовать на клиенте vshard API вряд ли хорошо, ведь правила вычисления шарда задаются на сервере. Причем это может быть и пользовательская функция, не обязательно vshard.router.bucket_id_strcrc32
- Писать дополнительную stored procedure (SP) router довольно накладно. Все это надо тестировать и поддерживать. Плюс нужно понимать нюансы работы vshard и кластера (а это нужно серьезно вникать, чтобы ничего не упустить). Ну и потом надо отслеживать, как бы там в кишках ничего не поменялось. То есть лучше, чтобы этим занимался "родной софт"

Поэтому и было такое пожелание. Но я понимаю, что это не так просто, т.к. в crud такой функциональности нет, а java-connector сейчас лишь проксирует вызовы crud
