### ISSUE TITLE
Implement API to pass 'fields' parameter to CRUD library

### ISSUE THREAD

**Issue by Thorwinz** [tarantool/cartridge-java#236]
В java любая crud операция возвращает всегда все поля (весь tuple целиком). в crud есть возможность задать в opts столбцы (fields), которые нужно вернуть, но в cartridge-driver 0.7.2 это задать нельзя, opts там хардкодится, единственное, что ставится, это таймаут.  нельзя ли ликвидировать "разрыв" в функциональности между java и crud ?

к примеру, в кортеже 30 полей, и я не могу выбрать одно поле, только все 30. 
имеется в виду:

space = tntClient.getClient().space(SPACE_NAME);
space.select(Conditions.any()) — возвращает все поля, нет возможности задать нужное (ые), condition для примера

тоже  самое replace/update/upsert/delete

гоняют по сети впустую данные

**Comment by vlalykin** [comment]
было бы неплохо оформить это как "returning"-параметры (так понятно любому, кто работает с БД), сейчас отсутствие параметра означает "все поля", но необходимо также полностью исключить параметры из результата, например, для insert/replace/update и т.д. часто не нужно возвращать вообще ничего, хотя jdbc всегда возвращает кол-во записей, которые добавлены/изменились/удалились. Может быть, надо сделать также

**Comment by Totktonada** [comment]
См. также https://github.com/tarantool/crud/issues/267 (не реализовано в crud на текущий момент).

**Comment by ArtDu** [comment]
Стоит разбить эту задачи на несколько

**Comment by ArtDu** [comment]
Blocked by #272 because driver should parse metadata from crud. We can't get field by field name if we don't know position and It will frustrate users 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/22258443/192274750-a0aeb262-95b2-4af2-8c71-383ca034380c.png">
