### ISSUE TITLE
Weird behaviour of JVM old-gen in architecture with HAPROXY

### ISSUE THREAD

**Issue by antonbashir** [tarantool/cartridge-java#238]
I have next context:

1. JVM service with cartridge-java 0.8.0 connector. No additional tnt modules. There are some clients inside the module with 50 connections in every. Clients are creating during boot and are not recreating later. Clients are connecting to HAPROXY. 
2. HAPROXY with next configuration:
```
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3
	maxconn 5000
    tune.ssl.cachesize 1000000
    nbproc  6
    cpu-map  1 0
    cpu-map  2 1
    cpu-map  3 2
    cpu-map  4 3
    cpu-map  5 4
    cpu-map  6 5
    master-worker

defaults
	log	global
	mode	http
	maxconn 5000
	option	dontlognull
    timeout server  60000

frontend stats
	bind *:10000
	stats enable
	stats uri /
	stats refresh 10s

listen scheduler-storage-mutable
    bind *:9003
    mode tcp
    option httpchk GET /isMaster
	option clitcpka
	option srvtcpka
	option tcpka
	option prefer-last-server
    balance source
    http-check expect status 200
    default-server inter 5s fall 3 rise 2 on-marked-down shutdown-sessions
    server storage-1 10.26.105.61:9002 maxconn 500 check port 9012
    server storage-2 10.26.105.62:9002 maxconn 500 check port 9012
    server storage-3 10.42.126.59:9002 maxconn 500 check port 9012

listen scheduler-storage-immutable
    bind *:9004
    mode tcp
    option httpchk GET /isMaster
	option clitcpka
	option srvtcpka
	option tcpka
	option prefer-last-server
    balance source
    http-check expect status 500
    default-server inter 5s fall 3 rise 2 on-marked-down shutdown-sessions
    server storage-1 10.26.105.61:9002 maxconn 500 check port 9012
    server storage-2 10.26.105.62:9002 maxconn 500 check port 9012
    server storage-3 10.42.126.59:9002 maxconn 500 check port 9012
```
3. Three Tarantool 2.8.4 instances behind the haproxy with http endpoint /isMaster for checking master status. 
4. Every 20 seconds my module is waking up and starting execute requests to haproxy. Every request is fast and short.

The problem is that periodically connector recreates connections which means recreation of Netty channels. 
Initiation of  the reconnection is here (/io/netty/channel/nio/AbstractNioByteChannel.java:156, close = true). 

There is the result after some days of module runtime:
![image](https://user-images.githubusercontent.com/33657862/179603640-6a8099a5-6388-4ad2-b959-f358fc0aa830.png)

In the heap dump were a lot of `TarantoolConnectionImpl` and `io.tarantool.driver.api.connection.TarantoolConnectionSelectionStrategies$ParallelRoundRobinStrategy$$Lambda` instances

As solution I removed option `timeout server  60000` from the HAPROXY configuration and recreations have stopped, also 
old-gen has stopped growing.

I've not found the main reason of old-gen leak but I though this case could be interested and made the issue.

**Comment by Elishtar** [comment]
Hi Anton, thank you for the detailed description. We will investigate this case and try to  generate some improvement
