### ISSUE TITLE
Открывает много соединений

### ISSUE THREAD

**Issue by SamVicV** [tarantool/cartridge-java#240]
Доброго времени суток.

Имеется сервис с реализацией Кластерного клиента. Сервис подключается по одному адресу и получает список роутеров. Сервис работает 24/7.
При запуске видно, что он подключается ко всем роутерам (норма):

![image](https://user-images.githubusercontent.com/47240120/180408391-2d783bc0-644b-4d76-b8d0-418d3aa27ae0.png)

Но через некоторое время количество открытых портов увеличивается, т.е. новые открывает, а старые не закрывает (проблема):

![image](https://user-images.githubusercontent.com/47240120/180408628-ae51377f-2a47-46e5-9064-239632ce3ff1.png)

Проблема в том, что количество открытых портов со временем увеличивается на столько, что забивает весь доступный пул в системе. И это касается не только списка роутеров, но и подключений "на себя", т.е. количество открытых портов с 127.0.0.1 подключаются на 127.0.0.1.

![image](https://user-images.githubusercontent.com/47240120/180409586-74c8687d-ac71-44de-b013-dbe5f09c4a27.png)

Подобные данные получаю через команду 

![image](https://user-images.githubusercontent.com/47240120/180410031-0f1a483c-3e21-4d70-a709-b55a8c538fdb.png)

Баг ли это?

**Comment by ArtDu** [comment]
Hi, can you provide version of cartridge-driver and your TarantoolClient config? We'll see what went wrong

**Comment by SamVicV** [comment]
cartridge-driver 0.7.2

```
public void buildClient(ConnectParams params){
        TarantoolCredentials credentials = new SimpleTarantoolCredentials(params.getLogin(), params.getPassword());

        TarantoolClientConfig config = TarantoolClientConfig.builder()
                .withCredentials(credentials)
                .build();

        tsAddresses = new ArrayList<>();
        // getHosts содержит только одно значение
        for(String item : params.getHosts()){
            tsAddresses.add(new TarantoolServerAddress(item, params.getPort()));
        }

        if (!params.hasRoutersFunction())
            params.setRoutersFunction("get_routers_c");

        BinaryClusterDiscoveryEndpoint endpoint = new BinaryClusterDiscoveryEndpoint.Builder()
                .withClientConfig(config)
                .withEntryFunction(params.getRoutersFunction())
                .withEndpointProvider(new TarantoolClusterAddressProvider() {
                    @Override
                    public Collection<TarantoolServerAddress> getAddresses() {
                        return tsAddresses;
                    }
                })
                .build();

        TarantoolClusterDiscoveryConfig clusterDiscoveryConfig = new TarantoolClusterDiscoveryConfig.Builder()
                .withEndpoint(endpoint)
                .withDelay(params.getRoutersDelay()) 
                .build();

        addressProvider = new ScbBinDiscoveryClusterAddressProvider(clusterDiscoveryConfig, params.getPort());

        TarantoolClientBuilder cb = TarantoolClientFactory.createClient()
                .withCredentials(params.getLogin(), params.getPassword()) 
                .withAddressProvider(addressProvider)
                .withConnectionSelectionStrategy(getConnectionSelectionStrategy())
        ;
        if (params.getConnectTimeout() > 0)
            cb.withConnectTimeout(params.getConnectTimeout());
        if (params.getReadTimeout() > 0)
            cb.withReadTimeout(params.getReadTimeout());
        if (params.getRequestTimeout() > 0)
            cb.withRequestTimeout(params.getRequestTimeout());

        client = cb.build();
    }
```

**Comment by akudiyar** [comment]
@SamVicV
1. Would you mind showing also the algorithm for retrieving the new addresses? Is it possible that the new addresses contain both old ones and new ones? 
2. What is the value for `connections` setting?

**Comment by SamVicV** [comment]
```
local function get_routers_c()
    local function table_contains(table, element)
        for _, value in pairs(table) do
            if value:find(element) then
                return true
            end
        end
        return false
    end

    local servers, err = cartridge.admin_get_servers()
    local routers = {}

    for _, server in pairs(servers) do
        if server.replicaset ~= nil then
			if table_contains(server.replicaset.roles, 'route') and server.status == 'healthy' and not server.disabled then
				routers[server.uuid] = {
					status = server.status,
					uuid = server.uuid,
					uri = server.uri,
					priority = server.priority
				}
			end
        end
    end

    return routers
end
```

Дальше отсев по порту:

```
public class ScbBinDiscoveryClusterAddressProvider extends BinaryDiscoveryClusterAddressProvider {
    private final int port;

    public ScbBinDiscoveryClusterAddressProvider(TarantoolClusterDiscoveryConfig discoveryConfig, int port) {
        super(discoveryConfig);
        this.port = port;
    }

    /**
     * Полученные список серверов, которые могут использоваться для подключения, фильтруется по порту
     */
    @Override
    protected Collection<TarantoolServerAddress> discoverAddresses() {
        Collection<TarantoolServerAddress> list = super.discoverAddresses();
        list.removeIf(v -> v.getPort() != port);
        return list;
    }
}
```

**Comment by SamVicV** [comment]
Откуда брать **connections**?

**Comment by bitgorbovsky** [comment]
@SamVicV

Also, which connectionSelectionStrategy are you using?

**Comment by SamVicV** [comment]
![image](https://user-images.githubusercontent.com/47240120/181251250-eeddfd84-adb1-43c2-9e46-43a04cd21d40.png)

**Comment by SamVicV** [comment]
> @SamVicV
> 
> Also, which connectionSelectionStrategy are you using?

PARALLEL_ROUND_ROBIN

**Comment by bitgorbovsky** [comment]
@SamVicV 

Thank you, I'll dig this problem. One additional question: why you set routersDelay to 1? It's in milliseconds, so, cluster discovery will try to scan addresses every millisecond. Probably it matters in your case.

**Comment by SamVicV** [comment]
Да, как в примере

```
TarantoolClusterDiscoveryConfig clusterDiscoveryConfig = new TarantoolClusterDiscoveryConfig.Builder()
                .withEndpoint(endpoint)
                .withDelay(1) // node information refresh delay
                .build();
```

Не увидел рекомендаций по этому параметру, поэтому оставил как в примере. Если дело может быть в нем, то какие рекомендации можете дать?

**Comment by bitgorbovsky** [comment]
It's just my assumption :) You can increase delay, it depends on your environment. For example, try to set delay like 100 milliseconds, and observe, what changed

**Comment by SamVicV** [comment]
Это точно может влиять или просто оптимизация?

**Comment by SamVicV** [comment]
Постоянный рост открытых портов оказался моей проблемой.
Однако, при открытых 5 портах к Тарантулу, оказалось открыто 64 порта на 127.0.0.1. 
Есть ли возможность как-то это исправить?

**Comment by bitgorbovsky** [comment]
@SamVicV 
Добрый день!
А можете рассказать подробнее, как вы выяснили, что это проблема именно на вашей стороне, что помогло? Или это не относилось вообще к cartridge-java?

По поводу 64 портов - вы пробовали ограничить количество соединений? С помошью вызова `.withConnections(int)` у конфигуратора?

**Comment by SamVicV** [comment]
@bitgorbovsky
Добрый день.
С моей стороны была ошибка, что закрытие соединения каким-то образом оказалось внутри `try...catch`, а соединение открывалось несколько раз в сутки.
По поводу `.withConnections(int)` - в описании метода написано, что по умолчанию значение равно 1, т.е. уменьшить никак, а увеличивать я не увеличивал.

Я сделал тестовое приложение с моим клиентом, где просто открывается соединение с Тарантулом и получается список серверов через кластерный механизм. 
Подключился по одному адресу, получил список из 4 адресов, а в итоге: 5 открытых портов к Тарантулу и 64 порта к 127.0.0.1.

**Comment by bitgorbovsky** [comment]
@SamVicV спасибо за подробный ответ!
А можете посмотреть, какой именно процесс открывает эти 64 порта?

**Comment by SamVicV** [comment]
процесс моего клиента, проверяю через `netstat` как описано выше

**Comment by bitgorbovsky** [comment]
@SamVicV добрый день!

К сожалению, проблему с открытием лишних портов мы воспроизвести не смогли на данный момент, поэтому issue закрываем. Советуем вам взять последнюю версию драйвера. Если же проблема повторится, то откроем тикет обратно :)

**Comment by SamVicV** [comment]
Я нашел проблемное место
![image](https://user-images.githubusercontent.com/47240120/182346968-ad3c2eaf-11ac-48e5-879a-a86b9371d21d.png)
По умолчанию, если передается значение 0 для кол-ва потоков, в netty выбирается исходя из кол-ва процессоров
`private static final int DEFAULT_EVENT_LOOP_THREADS = Math.max(1, SystemPropertyUtil.getInt("io.netty.eventLoopThreads", NettyRuntime.availableProcessors() * 2));`
В моем случае это = 24. При этом создается в 2 раза больше потоков в данном месте
![image](https://user-images.githubusercontent.com/47240120/182347646-34379868-9113-4238-b89f-b4418a2d2111.png)

Очень помогло бы, если бы была возможность указывать кол-во потоков или, если такой функционал есть, то просьба указать место где нужно дописать.

**Comment by akudiyar** [comment]
@SamVicV thanks for report, I created a new issue for this: https://github.com/tarantool/cartridge-java/issues/245
