### ISSUE TITLE
Add an option for specifying the number of Netty threads

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-java#245]
Related discussion: https://github.com/tarantool/cartridge-java/issues/240#issuecomment-1202276901

Currently, the number of threads is not passed to the Netty event loop. We need to add an option to TarantoolConfig (+builder) for specifying the number of threads with default 0.

**Comment by ArtDu** [comment]
We can pass a parameter to the `io.netty.eventLoopThreads` property and it should work.

```
DEFAULT_EVENT_LOOP_THREADS = Math.max(1, SystemPropertyUtil.getInt(
                "io.netty.eventLoopThreads", NettyRuntime.availableProcessors() * 2));
```
