### ISSUE TITLE
Integration tests are too long

### ISSUE THREAD

**Issue by isopov** [tarantool/cartridge-java#25]
Installing EPEL repository seems a long action that can be omitted taking docker image already containing it.

**Comment by akudiyar** [comment]
I agree, but I had the intention of using only the official Tarantool images. But, I expected that the test image layers will be built once and then reused and it seemed to work, do you see something different?

I see two possible ways of improving the IT running time:
 - Improve the tests (reuse images, use named images, etc.)
 - Improve the base Tarantool images
