### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Elishtar** [tarantool/cartridge-java#252]
Check and fix info and code examples in readme

**Comment by ArtDu** [comment]
@iDneprov а зачем ты закрыл тикет?

**Comment by iDneprov** [comment]
This ticket was opened to test the connector examples and to edit them if necessary. After I corrected everything in the [update-readme](https://github.com/tarantool/cartridge-java/tree/update-readme) branch, we decided that we would write new documentation.
