### ISSUE TITLE
Rename cartridge-java driver

### ISSUE THREAD

**Issue by ArtDu** [tarantool/cartridge-java#286]
Possible names:
- jtd(java tarantool driver)
- tarantool-driver
- jatt (java-tt)

**Comment by bitgorbovsky** [comment]
Rambo 😂 (Russian "таран" in English is being translated as "ram")

**Comment by bitgorbovsky** [comment]
HARD - yet another tarantol dirver👀

**Comment by ArtDu** [comment]
tarantool-java-driver
tarantool-iproto-java

**Comment by dkasimovskiy** [comment]
Won't do
