### ISSUE TITLE
Add ability to use auto converter from cartridge-java 

### ISSUE THREAD

**Issue by ArtDu** [tarantool/cartridge-java#320]
It's especially needed for cartridge-springdata

**Comment by akudiyar** [comment]
This ticket needs a broader description. Like a link to the Spring Data code.

**Comment by ArtDu** [comment]
https://github.com/tarantool/cartridge-springdata/blob/adbeeb55b1cab3b498e765bad6ffb9b8ce8105d2/src/main/java/org/springframework/data/tarantool/core/TarantoolTemplate.java#L125-L141

**Comment by akudiyar** [comment]
The ticket is about a MsgPack's map <-> Java Map converter, isn't it?

**Comment by ArtDu** [comment]
> The ticket is about a MsgPack's map <-> Java Map converter, isn't it?

Not really, it's about we have `@Query(TUPLE=AUTO)` that can convert all basic tuple types and primitives(crud response -> TarantoolResult, box response -> TarantoolResult, IntegerValue -> Integer, ArrayValue -> ArrayList(if metadata isn't exist in response type)) and we use create special mapper for it via crutches
