### ISSUE TITLE
Ограничение бесконтрольной нагрузки

### ISSUE THREAD

**Issue by vlalykin** [tarantool/cartridge-java#332]
cartridge-java устанавливает какие то правила/ограничения нагрузки при асинхронной работе ? что будет, если подать слишком много запросов ?) 

Судя по коду в RequestFutureManager, сейчас потенциально можно ожидать OutOfMemory:

```
    private final Map<Long, TarantoolRequestMetadata> requestFutures = new ConcurrentHashMap<>();

    public <T> CompletableFuture<T> submitRequest( ... ) {
        ...
        requestFutures.put(requestId, new TarantoolRequestMetadata(requestFuture, resultMapper));
        ...
    }

```
Хотелось бы иметь какую то настройку, чтобы недопустить outOfMemory. может быть она есть и я ее не вижу ?
Как следует поступать для ограничения бесконтрольной нагрузки и можно ли что то тут доработать ? 
первое, что приходит в голову - использовать блокирующую очередь, не позволяющую вставить более чем N запросов, на которые еще не получен ответ. Если вставляется N+1 запрос, то поток ставится на ожидание.

**Comment by akudiyar** [comment]
Hi, thanks for a good ticket. I see it is more a customer problem to control the cluster load (say, count the amount of finished tasks or use some metrics from the cluster). It seems rather a had problem to develop an universal algorithm of controlling the back pressure. However, providing an interface for the customers for them to be able to inject the back pressure handlers in the request processing seems to be a nice change.

**Comment by vlalykin** [comment]
Hi
Here we are not talking about some kind of universal algorithm, but only about the fact that any queue should not grow to infinity. Any resource must be limited, as is done, for example, in a blocking queue (the writer is put on hold if the queue is full).
since the library uses the means to ensure the interaction of threads (ConcurrentHashMap, and perhaps netty also has such a mechanism?), adding new such structures by the customer will lead to a decrease in performance. It seems that it is better to have an optimized inter-thread communication mechanism built into the library itself

**Comment by akudiyar** [comment]
@vlalykin that's a good point that we may provide some configurable limitations for the internal queue, but I want to emphasize that the necessity of such limitations depends on the environment - say, for the same physical server running a Tarantool cluster, the client limitation will, on one hand, strongly depend on the presence of other clients and the internal load of the cluster, and on the other hand, on the physical limitations of the client machine, which may be a VM with non-100% resource guarantees, thus having variable CPU/RAM availability and so on. So limiting the internal queue size or the number of threads is a partial solution and will transfer too much control to the side of a driver user.

I suggest thinking about a solution when we can achieve the following goals:
 - provide an extension point for the users so they are able to limit the request frequency based on some external metrics. At least that will enable using of the Taratnool and system metrics and more elastic adaptation to a non-uniform workload.
 - provide basic implementations of limiting algorithms as we have done with the retries. These algorithms will use the internal driver metrics, which we still need to implement first.
 
 So, the more important task beforehand seems to be implementing the internal driver metrics. BTW, looking at what we have in Netty on that matter may also help, some advanced users may benefit immediately from more granular control over the Netty backend.

**Comment by vlalykin** [comment]
> akudiyar

it sounds good, but is it feasible in practice? users do not have enough knowledge about the operation of the cluster, and too much of a good thing is good for nothing (Лучшее-враг хорошего). 
Of course, it would be nice to have such advanced mechanisms.
I'm still focusing on the resources of one specific client computer. If we see that the CPU becomes equal to 100%, then this is definitely very bad. And that means you need at least a simple setting in the form of the maximum amount of "something there" (for example, unprocessed requests to the server). Although this threshold is not based on the current state of the cluster as a whole, it serves only as a fuse, protection against overheating. And this does not contradict the goals that you described above.
that is: one does not interfere with the other. but simple and clear restrictions make the system more reliable

**Comment by akudiyar** [comment]
@vlalykin A simple straightforward solution with just a "limit of requests" will lead to a saw-like load pattern, where requests "burst" the limit and then many of them start failing with timeouts in the client code because the "queue" is full. It doesn't look like an improvement. I believe that we need to reuse our retry algorithms here at least so that the requests will be postponed instead of just failing with an error, for example. And postponing means re-scheduling them with a new frequency that requires some calculation. Just simply slowing down all requests with a constant delay is also too rigid and may interrupt real business scenarios.
That's why I insist on providing an extension endpoint and not a simple one-positional "lever" that can make things just worse. 
Regarding people not knowing all the internal nuances of how Tarantool cluster works - I think exactly about that. Just providing a "limit" means that it somehow could magically help, but it won't. But the users should know their load and they can control the pace of the cluster load using that information dynamically.

**Comment by vlalykin** [comment]
@akudiyar

сейчас есть проблема: если лить в тарантул больше, чем он успевает переварить, то теоретически я ожидаю OutOfMemory, но на практике имею 100% CPU. При этом оба варианта неприемлемы и как-то этого нужно избежать. 

Поэтому все равно в этом "extension endpoint" д.б. возможность управлять размерами внутренних очередей (пусть динамически, с учетом  мониторинга). Потому что я не вижу в большинстве сценариев возможности реагировать как то иначе, кроме как сидеть на ожидании. Единственный способ избежать наводнения - прикрыть шлюзы поворотом вентиля, тем самым мы ограничим нашу входную пропускную способность для внешних клиентов (по факту это другие микросервисы).  

Если же доступа к размеру очереди не будет, то "extension endpoint" просто станет тем местом, где мы вынуждены будем организовывать еще одну очередь самостоятельно. и нам хотелось бы этого, естественно, избежать, т.к. однотипные задачи будут решаться в разных местах и потреблять намного больше ресурсов (кстати отличная иллюстрация пагубности такого подхода - текущий механизм повторов. там как раз и имеем CPU 100%, оверхед большой, хотя до повторов дело даже не доходит (requestTimeout слишком большой). И это потому, что там создается свой велосипед, вместо того, чтобы использовать уже имеющуюся "очередь".

По повторам: если повторы есть, то они будут конкурировать с новыми запросами за место в "ограниченной очереди" для запросов к немедленному выполнению. Что делать, если уже и повторы некуда складывать ? надо ли их вообще пытаться делать в таких ситуациях или нужен суммарный лимит на "повторы + активные запросы" ? вот вам пожалуйста еще возможные настройки для "extension endpoint"

**Comment by akudiyar** [comment]
@vlalykin
1. Внутренних очередей нет никаких, кроме очереди запросов на входе Тарантула. Если Тарантул не может переварить, то проблема не в коннекторе, так как она будет повторяться с любым клиентским кодом - хоть на Питоне, хоть на Луа. Однако драйвер сохраняет внутри информацию о запросах, поэтому смысла держать в памяти больше запросов, чем переваривает Тарантул, также нет - это выльется в OOM. То, что запросы начинают отваливаться по таймауту из-за 100% CPU - это и есть естественный лимит, и при искуственном лимите будет происходить то же самое, только Тарантул будет недозагружен, или точно также перегружен, в зависимости от количества клиентов. Поэтому я считаю какие-либо лимиты неэффективной мерой, хотя в Тарантуле есть для этого настройки - например, `net_msg_max`. 
Повтор запросов, отвалившихся с таймаутом, с экспоненциальной или любой другой "умной" задержкой, которая считается по нагрузке, выглядит более жизнеспособно и много где применяется.

2. Проблемы с алгоритмом повторов действительно были, так как там использовалось синхронное ожидание, но сейчас они решены (с версии 0.10.1) и оверхед на повторы должен быть достаточно минимальный. Не хватает только более умных алгоритмов задержки, чем простые, которые есть сейчас, но их легко написать самостоятельно. Мы планируем добавить дефолтную стратегию с экспоненциальной задержкой, есть на это задача #316. C таким типом задержки кластер будет эффективно разгружаться, а клиенты - ждать, в отличие от дефолтной сейчас фиксированной задержки. 

3. Повторы за место "в очереди" не конкурируют (эффект будет более заметен с экспоненциальной задержкой), так как "встают" в неё с задержкой, пропуская вперёд более новые запросы. Среди дефолтных стратегий повторов уже есть варианты с ограничением времени повторов и количества попыток, и также никаких проблем не вижу реализовать свой алгоритм в клиентском коде. Лучше всего, если он будет "умным" и дополнительно будет учитывать метрики кластера и клиентского приложения, о которых драйверу внутри знать не нужно.

4. Клиентский код должен быть написан в  парадигме параллельной асинхронной обработки запросов и организован таким образом, что загрузка или получение большого объёма данных разделены на пачки, каждая из которых отправляется только после обработки предыдущей. Делать такой механизм в коде драйвера не вижу смысла, так как в таком случае либо всё равно не будет выигрыша по памяти, так как все запросы будут сохраняться в ещё одной очереди, либо драйверу придется возвращать ошибку при достижении лимита, и тогда в клиентском приложении придется реализовывать ещё один механизм повторов или возвращать неприятную ошибку пользователю. Вместо этого надо в клиентском коде сразу использовать преимущества асинхронной обработки запросов.

**Comment by akudiyar** [comment]
P.S. I think that blocking the client thread is rather a bad idea, because the client application may become stuck and fail with some unexpected exception, and also all the driver interface methods are asynchronous, which means blocking on any such method call will greatly surprise the users.

I believe that a better way is to implement the driver metrics and the users will then be able to control the load according to the memory usage, for example. Picking up the right queue size without considering the queue item sizes looks like picking up a secure random by a single "fair" dice roll.

**Comment by akudiyar** [comment]
@ArtDu would you mind adding here a summary of ticket 45899? I don't have access to it. Probably that should be a new ticket.

@vlalykin Thanks for the details. Real use cases look definitely better than the initial abstract description. Would you mind adding an example of the desired behavior for a single API method? That will allow understanding better of what we can offer.

**Comment by ArtDu** [comment]
> @ArtDu would you mind adding here a summary of ticket 45899? I don't have access to it. Probably that should be a new ticket.

It's nothing intersting there. The ticket described that client generates more than 10k rps from carg-java to one instance ofz Tarantool and Tarantool doesn't have enough resources of tx thread to respond within 2 seconds. 

In my opinion, the feature that was described by @vlalykin need to implement if a lot of clients need it. Now we don't have problems with it. Clients usually control their load in application code or in load balancers

**Comment by vlalykin** [comment]
@ArtDu 

2 cекунды - это тикет 45895, а не 45899. и там нет ничего про один экземпляр (он не один), но это вообще неважно. потому что проблема в клиенте, а не в сервере. Но здесь не об этом.

в тикете 45899 речь идет о 100% CPU: 
- если retry не включены, используется около 60% CPU
- достаточно просто включить retry, например с очень большим таймаутом (заведомо большим, чем время работы теста), и нагрузка вырастает до 100%. 

Там просто иллюстрируется, что накладные расходы механизма повторов очень большие. 
> Если точнее, то:
> - без повторов - создается только один таск в одном шедулере в
RequestFutureManager
> - с повторами - создается три разных таска в двух шедулерах. И еще executor
(я указываю однопоточный), который постоянно выполняет запуск асинхронных
процедур. Все это добро съедает все ядра даже тогда, когда время самих
повторов не наступает

Применительно к основному тикету "ограничение беконтрольной нагрузки" - здесь прямая связь. Выше предлагается ограничиться метриками мониторинга и переложить проблему балансировки нагрузки на клиента. 

Я же показываю, что даже в коде драйвера сейчас есть проблема неэффективного использования ресурсов, а что будет, если клиент начнет реализовать свои самописные механизмы контроля дополнительно к имеющимся ?

**Comment by Thorwinz** [comment]
@vlalykin напоминаю, что заявки на реализацию фичей принимаются через иной механизм (уточнить у отв. менеджера) принятый у вас в компании. Согласуются и оплачиваются дополнительно.

**Comment by vlalykin** [comment]
@Thorwinz 
Если я вижу проблему - то сообщаю о ней. Не согласны - будем писать вокруг свои костыли. 
Но вообще, ограничение нагрузки - это вопрос зрелости продукта. Мне кажется, Вы сами должны быть заинтересованы. За чей счет развитие - это уже не мой вопрос.

**Comment by akudiyar** [comment]
I believe we need a doc page and an example of working with a massive amount of requests with the driver. Let's make a ticket for that before closing this issue.

**Comment by akudiyar** [comment]
See: https://github.com/tarantool/cartridge-java/issues/364

**Comment by ArtDu** [comment]
In my opinion, the task can be solved on top of the driver in the client's business code, if required. Limiting the load of business logic is a separate product that does not correlate with the load on the Tarantool, or the feature should be implemented in the Tarantool itself, but not in the connector. Because the bottleneck is Tarantool in those tests
