### ISSUE TITLE
If a request is failed due to the connection error, retry it after connection re-established 

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-java#53]
# Problem statement

This is an example of a built-in request retrying policy.

In case of connection failure, if there are in-flight requests, not submitted to the server, they should be resubmitted after the connection is restored (possible a new set of servers is received from disovery and the new connections are established). This must be a configurable request failure handling policy, bound to the specific kind of failures.

# Requirements

1. Different (including user-defined) request failure handlers must be supported, which allow dealing with request failures by the kind of error (Exception type?)
2. The request retry policy described above for connection failure error must be available by default.

**Comment by no1seman** [comment]
Well, it's good idea and will be great if it will be implemented following way or similar:

![Жаба ретрай](https://user-images.githubusercontent.com/17825302/102611203-88468480-413f-11eb-8a5f-10daf22b21b2.png)
