### ISSUE TITLE
Investigate high CPU utilization on MessagePack serialization operaitions

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/cartridge-java#96]
It's reported that tuples serialization with nested "maps" completely utitlize several CPUs with a single-threaded synchronous client data loader application. Need to benchmark the case for the following java type Map<String, <Map, String>> where the nested map contains about 250 items. Total size of tuple is about 2kb.  Client config uses 1 connection. cartridge-java v 0.4.1

**Comment by akudiyar** [comment]
Additional information:

 - The cluster has 8 routers, but only one router is used by the client
 - The client code uses batching with separation to several threads via a ThreadPoolExecutor where each  request does retry using Spring RetryTemplate and inside the retry blocks on `get()` (see below):
![image](https://user-images.githubusercontent.com/2381032/117989419-fa18a800-b344-11eb-92e7-3546ac9f77f7.png)
 - Each blocking operation is a call for a stored function, which looks like this:
![image](https://user-images.githubusercontent.com/2381032/117989755-3fd57080-b345-11eb-9394-114acc595029.png)

**Comment by akudiyar** [comment]
We need to write a performance auto-test and try to reproduce the conditions.
